package domain.currency_code;

import java.util.HashMap;
import java.util.Map;

public class CurrencyCodeRepository {

    private static final Map<String, CurrencyCode> currencyCodes = new HashMap<>();

    static {
        currencyCodes.put("AED", new CurrencyCode("AED", "UAE Dirham", "United Arab Emirates"));
        currencyCodes.put("AFN", new CurrencyCode("AFN", "Afghan Afghani", "Afghanistan"));
        currencyCodes.put("ALL", new CurrencyCode("ALL", "Albanian Lek", "Albania"));
        currencyCodes.put("AMD", new CurrencyCode("AMD", "Armenian Dram", "Armenia"));
        currencyCodes.put("ANG", new CurrencyCode("ANG", "Netherlands Antillian Guilder", "Netherlands Antilles"));
        currencyCodes.put("AOA", new CurrencyCode("AOA", "Angolan Kwanza", "Angola"));
        currencyCodes.put("ARS", new CurrencyCode("ARS", "Argentine Peso", "Argentina"));
        currencyCodes.put("AUD", new CurrencyCode("AUD", "Australian Dollar", "Australia"));
        currencyCodes.put("AWG", new CurrencyCode("AWG", "Aruban Florin", "Aruba"));
        currencyCodes.put("AZN", new CurrencyCode("AZN", "Azerbaijani Manat", "Azerbaijan"));
        currencyCodes.put("BAM", new CurrencyCode("BAM", "Bosnia and Herzegovina Mark", "Bosnia and Herzegovina"));
        currencyCodes.put("BBD", new CurrencyCode("BBD", "Barbados Dollar", "Barbados"));
        currencyCodes.put("BDT", new CurrencyCode("BDT", "Bangladeshi Taka", "Bangladesh"));
        currencyCodes.put("BGN", new CurrencyCode("BGN", "Bulgarian Lev", "Bulgaria"));
        currencyCodes.put("BHD", new CurrencyCode("BHD", "Bahraini Dinar", "Bahrain"));
        currencyCodes.put("BIF", new CurrencyCode("BIF", "Burundian Franc", "Burundi"));
        currencyCodes.put("BMD", new CurrencyCode("BMD", "Bermudian Dollar", "Bermuda"));
        currencyCodes.put("BND", new CurrencyCode("BND", "Brunei Dollar", "Brunei"));
        currencyCodes.put("BOB", new CurrencyCode("BOB", "Bolivian Boliviano", "Bolivia"));
        currencyCodes.put("BRL", new CurrencyCode("BRL", "Brazilian Real", "Brazil"));
        currencyCodes.put("BSD", new CurrencyCode("BSD", "Bahamian Dollar", "Bahamas"));
        currencyCodes.put("BTN", new CurrencyCode("BTN", "Bhutanese Ngultrum", "Bhutan"));
        currencyCodes.put("BWP", new CurrencyCode("BWP", "Botswana Pula", "Botswana"));
        currencyCodes.put("BYN", new CurrencyCode("BYN", "Belarusian Ruble", "Belarus"));
        currencyCodes.put("BZD", new CurrencyCode("BZD", "Belize Dollar", "Belize"));
        currencyCodes.put("CAD", new CurrencyCode("CAD", "Canadian Dollar", "Canada"));
        currencyCodes.put("CDF", new CurrencyCode("CDF", "Congolese Franc", "Democratic Republic of the Congo"));
        currencyCodes.put("CHF", new CurrencyCode("CHF", "Swiss Franc", "Switzerland"));
        currencyCodes.put("CLP", new CurrencyCode("CLP", "Chilean Peso", "Chile"));
        currencyCodes.put("CNY", new CurrencyCode("CNY", "Chinese Renminbi", "China"));
        currencyCodes.put("COP", new CurrencyCode("COP", "Colombian Peso", "Colombia"));
        currencyCodes.put("CRC", new CurrencyCode("CRC", "Costa Rican Colon", "Costa Rica"));
        currencyCodes.put("CUP", new CurrencyCode("CUP", "Cuban Peso", "Cuba"));
        currencyCodes.put("CVE", new CurrencyCode("CVE", "Cape Verdean Escudo", "Cape Verde"));
        currencyCodes.put("CZK", new CurrencyCode("CZK", "Czech Koruna", "Czech Republic"));
        currencyCodes.put("DJF", new CurrencyCode("DJF", "Djiboutian Franc", "Djibouti"));
        currencyCodes.put("DKK", new CurrencyCode("DKK", "Danish Krone", "Denmark"));
        currencyCodes.put("DOP", new CurrencyCode("DOP", "Dominican Peso", "Dominican Republic"));
        currencyCodes.put("DZD", new CurrencyCode("DZD", "Algerian Dinar", "Algeria"));
        currencyCodes.put("EGP", new CurrencyCode("EGP", "Egyptian Pound", "Egypt"));
        currencyCodes.put("ERN", new CurrencyCode("ERN", "Eritrean Nakfa", "Eritrea"));
        currencyCodes.put("ETB", new CurrencyCode("ETB", "Ethiopian Birr", "Ethiopia"));
        currencyCodes.put("EUR", new CurrencyCode("EUR", "Euro", "European Union"));
        currencyCodes.put("FJD", new CurrencyCode("FJD", "Fiji Dollar", "Fiji"));
        currencyCodes.put("FKP", new CurrencyCode("FKP", "Falkland Islands Pound", "Falkland Islands"));
        currencyCodes.put("FOK", new CurrencyCode("FOK", "Faroese Króna", "Faroe Islands"));
        currencyCodes.put("GBP", new CurrencyCode("GBP", "Pound Sterling", "United Kingdom"));
        currencyCodes.put("GEL", new CurrencyCode("GEL", "Georgian Lari", "Georgia"));
        currencyCodes.put("GGP", new CurrencyCode("GGP", "Guernsey Pound", "Guernsey"));
        currencyCodes.put("GHS", new CurrencyCode("GHS", "Ghanaian Cedi", "Ghana"));
        currencyCodes.put("GIP", new CurrencyCode("GIP", "Gibraltar Pound", "Gibraltar"));
        currencyCodes.put("GMD", new CurrencyCode("GMD", "Gambian Dalasi", "The Gambia"));
        currencyCodes.put("GNF", new CurrencyCode("GNF", "Guinean Franc", "Guinea"));
        currencyCodes.put("GTQ", new CurrencyCode("GTQ", "Guatemalan Quetzal", "Guatemala"));
        currencyCodes.put("GYD", new CurrencyCode("GYD", "Guyanese Dollar", "Guyana"));
        currencyCodes.put("HKD", new CurrencyCode("HKD", "Hong Kong Dollar", "Hong Kong"));
        currencyCodes.put("HNL", new CurrencyCode("HNL", "Honduran Lempira", "Honduras"));
        currencyCodes.put("HRK", new CurrencyCode("HRK", "Croatian Kuna", "Croatia"));
        currencyCodes.put("HTG", new CurrencyCode("HTG", "Haitian Gourde", "Haiti"));
        currencyCodes.put("HUF", new CurrencyCode("HUF", "Hungarian Forint", "Hungary"));
        currencyCodes.put("IDR", new CurrencyCode("IDR", "Indonesian Rupiah", "Indonesia"));
        currencyCodes.put("ILS", new CurrencyCode("ILS", "Israeli New Shekel", "Israel"));
        currencyCodes.put("IMP", new CurrencyCode("IMP", "Manx Pound", "Isle of Man"));
        currencyCodes.put("INR", new CurrencyCode("INR", "Indian Rupee", "India"));
        currencyCodes.put("IQD", new CurrencyCode("IQD", "Iraqi Dinar", "Iraq"));
        currencyCodes.put("IRR", new CurrencyCode("IRR", "Iranian Rial", "Iran"));
        currencyCodes.put("ISK", new CurrencyCode("ISK", "Icelandic Króna", "Iceland"));
        currencyCodes.put("JEP", new CurrencyCode("JEP", "Jersey Pound", "Jersey"));
        currencyCodes.put("JMD", new CurrencyCode("JMD", "Jamaican Dollar", "Jamaica"));
        currencyCodes.put("JOD", new CurrencyCode("JOD", "Jordanian Dinar", "Jordan"));
        currencyCodes.put("JPY", new CurrencyCode("JPY", "Japanese Yen", "Japan"));
        currencyCodes.put("KES", new CurrencyCode("KES", "Kenyan Shilling", "Kenya"));
        currencyCodes.put("KGS", new CurrencyCode("KGS", "Kyrgyzstani Som", "Kyrgyzstan"));
        currencyCodes.put("KHR", new CurrencyCode("KHR", "Cambodian Riel", "Cambodia"));
        currencyCodes.put("KID", new CurrencyCode("KID", "Kiribati Dollar", "Kiribati"));
        currencyCodes.put("KMF", new CurrencyCode("KMF", "Comorian Franc", "Comoros"));
        currencyCodes.put("KRW", new CurrencyCode("KRW", "South Korean Won", "South Korea"));
        currencyCodes.put("KWD", new CurrencyCode("KWD", "Kuwaiti Dinar", "Kuwait"));
        currencyCodes.put("KYD", new CurrencyCode("KYD", "Cayman Islands Dollar", "Cayman Islands"));
        currencyCodes.put("KZT", new CurrencyCode("KZT", "Kazakhstani Tenge", "Kazakhstan"));
        currencyCodes.put("LAK", new CurrencyCode("LAK", "Lao Kip", "Laos"));
        currencyCodes.put("LBP", new CurrencyCode("LBP", "Lebanese Pound", "Lebanon"));
        currencyCodes.put("LKR", new CurrencyCode("LKR", "Sri Lanka Rupee", "Sri Lanka"));
        currencyCodes.put("LRD", new CurrencyCode("LRD", "Liberian Dollar", "Liberia"));
        currencyCodes.put("LSL", new CurrencyCode("LSL", "Lesotho Loti", "Lesotho"));
        currencyCodes.put("LYD", new CurrencyCode("LYD", "Libyan Dinar", "Libya"));
        currencyCodes.put("MAD", new CurrencyCode("MAD", "Moroccan Dirham", "Morocco"));
        currencyCodes.put("MDL", new CurrencyCode("MDL", "Moldovan Leu", "Moldova"));
        currencyCodes.put("MGA", new CurrencyCode("MGA", "Malagasy Ariary", "Madagascar"));
        currencyCodes.put("MKD", new CurrencyCode("MKD", "Macedonian Denar", "North Macedonia"));
        currencyCodes.put("MMK", new CurrencyCode("MMK", "Burmese Kyat", "Myanmar"));
        currencyCodes.put("MNT", new CurrencyCode("MNT", "Mongolian Tögrög", "Mongolia"));
        currencyCodes.put("MOP", new CurrencyCode("MOP", "Macanese Pataca", "Macau"));
        currencyCodes.put("MRU", new CurrencyCode("MRU", "Mauritanian Ouguiya", "Mauritania"));
        currencyCodes.put("MUR", new CurrencyCode("MUR", "Mauritian Rupee", "Mauritius"));
        currencyCodes.put("MVR", new CurrencyCode("MVR", "Maldivian Rufiyaa", "Maldives"));
        currencyCodes.put("MWK", new CurrencyCode("MWK", "Malawian Kwacha", "Malawi"));
        currencyCodes.put("MXN", new CurrencyCode("MXN", "Mexican Peso", "Mexico"));
        currencyCodes.put("MYR", new CurrencyCode("MYR", "Malaysian Ringgit", "Malaysia"));
        currencyCodes.put("MZN", new CurrencyCode("MZN", "Mozambican Metical", "Mozambique"));
        currencyCodes.put("NAD", new CurrencyCode("NAD", "Namibian Dollar", "Namibia"));
        currencyCodes.put("NGN", new CurrencyCode("NGN", "Nigerian Naira", "Nigeria"));
        currencyCodes.put("NIO", new CurrencyCode("NIO", "Nicaraguan Córdoba", "Nicaragua"));
        currencyCodes.put("NOK", new CurrencyCode("NOK", "Norwegian Krone", "Norway"));
        currencyCodes.put("NPR", new CurrencyCode("NPR", "Nepalese Rupee", "Nepal"));
        currencyCodes.put("NZD", new CurrencyCode("NZD", "New Zealand Dollar", "New Zealand"));
        currencyCodes.put("OMR", new CurrencyCode("OMR", "Omani Rial", "Oman"));
        currencyCodes.put("PAB", new CurrencyCode("PAB", "Panamanian Balboa", "Panama"));
        currencyCodes.put("PEN", new CurrencyCode("PEN", "Peruvian Sol", "Peru"));
        currencyCodes.put("PGK", new CurrencyCode("PGK", "Papua New Guinean Kina", "Papua New Guinea"));
        currencyCodes.put("PHP", new CurrencyCode("PHP", "Philippine Peso", "Philippines"));
        currencyCodes.put("PKR", new CurrencyCode("PKR", "Pakistani Rupee", "Pakistan"));
        currencyCodes.put("PLN", new CurrencyCode("PLN", "Polish Złoty", "Poland"));
        currencyCodes.put("PYG", new CurrencyCode("PYG", "Paraguayan Guaraní", "Paraguay"));
        currencyCodes.put("QAR", new CurrencyCode("QAR", "Qatari Riyal", "Qatar"));
        currencyCodes.put("RON", new CurrencyCode("RON", "Romanian Leu", "Romania"));
        currencyCodes.put("RSD", new CurrencyCode("RSD", "Serbian Dinar", "Serbia"));
        currencyCodes.put("RUB", new CurrencyCode("RUB", "Russian Ruble", "Russia"));
        currencyCodes.put("RWF", new CurrencyCode("RWF", "Rwandan Franc", "Rwanda"));
        currencyCodes.put("SAR", new CurrencyCode("SAR", "Saudi Riyal", "Saudi Arabia"));
        currencyCodes.put("SBD", new CurrencyCode("SBD", "Solomon Islands Dollar", "Solomon Islands"));
        currencyCodes.put("SCR", new CurrencyCode("SCR", "Seychellois Rupee", "Seychelles"));
        currencyCodes.put("SDG", new CurrencyCode("SDG", "Sudanese Pound", "Sudan"));
        currencyCodes.put("SEK", new CurrencyCode("SEK", "Swedish Krona", "Sweden"));
        currencyCodes.put("SGD", new CurrencyCode("SGD", "Singapore Dollar", "Singapore"));
        currencyCodes.put("SHP", new CurrencyCode("SHP", "Saint Helena Pound", "Saint Helena"));
        currencyCodes.put("SLE", new CurrencyCode("SLE", "Sierra Leonean Leone", "Sierra Leone"));
        currencyCodes.put("SOS", new CurrencyCode("SOS", "Somali Shilling", "Somalia"));
        currencyCodes.put("SRD", new CurrencyCode("SRD", "Surinamese Dollar", "Suriname"));
        currencyCodes.put("SSP", new CurrencyCode("SSP", "South Sudanese Pound", "South Sudan"));
        currencyCodes.put("STN", new CurrencyCode("STN", "São Tomé and Príncipe Dobra", "São Tomé and Príncipe"));
        currencyCodes.put("SYP", new CurrencyCode("SYP", "Syrian Pound", "Syria"));
        currencyCodes.put("SZL", new CurrencyCode("SZL", "Eswatini Lilangeni", "Eswatini"));
        currencyCodes.put("THB", new CurrencyCode("THB", "Thai Baht", "Thailand"));
        currencyCodes.put("TJS", new CurrencyCode("TJS", "Tajikistani Somoni", "Tajikistan"));
        currencyCodes.put("TMT", new CurrencyCode("TMT", "Turkmenistan Manat", "Turkmenistan"));
        currencyCodes.put("TND", new CurrencyCode("TND", "Tunisian Dinar", "Tunisia"));
        currencyCodes.put("TOP", new CurrencyCode("TOP", "Tongan Paʻanga", "Tonga"));
        currencyCodes.put("TRY", new CurrencyCode("TRY", "Turkish Lira", "Turkey"));
        currencyCodes.put("TTD", new CurrencyCode("TTD", "Trinidad and Tobago Dollar", "Trinidad and Tobago"));
        currencyCodes.put("TVD", new CurrencyCode("TVD", "Tuvaluan Dollar", "Tuvalu"));
        currencyCodes.put("TWD", new CurrencyCode("TWD", "New Taiwan Dollar", "Taiwan"));
        currencyCodes.put("TZS", new CurrencyCode("TZS", "Tanzanian Shilling", "Tanzania"));
        currencyCodes.put("UAH", new CurrencyCode("UAH", "Ukrainian Hryvnia", "Ukraine"));
        currencyCodes.put("UGX", new CurrencyCode("UGX", "Ugandan Shilling", "Uganda"));
        currencyCodes.put("USD", new CurrencyCode("USD", "United States Dollar", "United States"));
        currencyCodes.put("UYU", new CurrencyCode("UYU", "Uruguayan Peso", "Uruguay"));
        currencyCodes.put("UZS", new CurrencyCode("UZS", "Uzbekistani So'm", "Uzbekistan"));
        currencyCodes.put("VES", new CurrencyCode("VES", "Venezuelan Bolívar Soberano", "Venezuela"));
        currencyCodes.put("VND", new CurrencyCode("VND", "Vietnamese Đồng", "Vietnam"));
        currencyCodes.put("VUV", new CurrencyCode("VUV", "Vanuatu Vatu", "Vanuatu"));
        currencyCodes.put("WST", new CurrencyCode("WST", "Samoan Tālā", "Samoa"));
        currencyCodes.put("XAF", new CurrencyCode("XAF", "Central African CFA Franc", "CEMAC"));
        currencyCodes.put("XCD", new CurrencyCode("XCD", "East Caribbean Dollar", "Organisation of Eastern Caribbean States"));
        currencyCodes.put("XDR", new CurrencyCode("XDR", "Special Drawing Rights", "International Monetary Fund"));
        currencyCodes.put("XOF", new CurrencyCode("XOF", "West African CFA franc", "CFA"));
        currencyCodes.put("XPF", new CurrencyCode("XPF", "CFP Franc", "Collectivités d'Outre-Mer"));
        currencyCodes.put("YER", new CurrencyCode("YER", "Yemeni Rial", "Yemen"));
        currencyCodes.put("ZAR", new CurrencyCode("ZAR", "South African Rand", "South Africa"));
        currencyCodes.put("ZMW", new CurrencyCode("ZMW", "Zambian Kwacha", "Zambia"));
        currencyCodes.put("ZWL", new CurrencyCode("ZWL", "Zimbabwean Dollar", "Zimbabwe"));
    }

    public static CurrencyCode getCurrencyCode(String code) {
        return currencyCodes.get(code);
    }

    public static Map<String, CurrencyCode> getAllCurrencyCodes() {
        return currencyCodes;
    }
}
